# mypy: allow-untyped-defs
import dataclasses
import sys
from enum import Enum
from typing import Callable, Dict, List, Optional, Type

import sympy

import torch

from .. import cpp_builder, ir
from ..cpu_vec_isa import pick_vec_isa, VecAMX, VecAVX2, VecAVX512, VecISA
from ..utils import IndentedBuffer, parallel_num_threads
from ..virtualized import V
from .common import KernelTemplate
from .cpp_template_kernel import CppTemplateKernel
from .cpp_utils import DTYPE_TO_CPP, GemmBlocking, value_to_cpp


class LayoutType(Enum):
    NORMAL = 0
    VNNI2 = 1
    VNNI4 = 2


_IS_WINDOWS = sys.platform == "win32"


def get_restrict_keyword() -> str:
    if _IS_WINDOWS:
        # https://learn.microsoft.com/en-us/cpp/cpp/extension-restrict?view=msvc-170
        return "__restrict"
    else:
        return "__restrict__"


class CppMicroGemm:
    """
    A class that codegens a kernel that computes small-sized matrix multiplication.

    A micro GEMM kernel is responsible for register blocking, instruction selection,
    and other CPU architecture-specific optimizations.

    The subclasses need to override `codegen_define` to define the kernel function
    that is called by the code generated by `codegen_call`.
    """

    # TODO(jgong5): support constant shapes and lds as template args.
    DECLARE_KERNEL = r"""
template <bool accum>
inline void {{kernel_name}}(
{%- if kernel_extra_args_declare %}
    {{kernel_extra_args_declare}}
{%- endif %}
    const {{input_t}}* {{restrict_keyword}} A,
    const {{input2_t}}* {{restrict_keyword}} B,
    {{output_t}}* {{restrict_keyword}} C,
    int64_t M,
    int64_t N,
    int64_t K,
    int64_t lda,
    int64_t ldb,
    int64_t ldc,
    bool trans_b
)
"""

    def __init__(
        self,
        name,
        input_dtype,
        input2_dtype,
        output_dtype,
        compute_dtype,
        register_blocking,
        alpha=1,
    ) -> None:
        self.name = name
        self.input_dtype = input_dtype
        assert input2_dtype is not None
        self.input2_dtype = input2_dtype
        self.output_dtype = output_dtype
        self.compute_dtype = compute_dtype
        self.register_blocking = register_blocking
        self.alpha = alpha

    def get_common_options(self):
        if self.input_dtype == torch.uint8:
            assert self.compute_dtype == torch.int32
            assert self.output_dtype == torch.int32
            assert self.input2_dtype == torch.int8
        return {
            "torch": torch,
            "kernel_name": self.name,
            "input_dtype": self.input_dtype,
            "input2_dtype": self.input2_dtype,
            "output_dtype": self.output_dtype,
            "compute_dtype": self.compute_dtype,
            "input_t": DTYPE_TO_CPP[self.input_dtype],
            "input2_t": DTYPE_TO_CPP[self.input2_dtype],
            "output_t": DTYPE_TO_CPP[self.output_dtype],
            "compute_t": DTYPE_TO_CPP[self.compute_dtype],
            "alpha": self.alpha,
            "kernel_extra_args_declare": self.get_kernel_extra_args_declare(),
            "int8_gemm": self.input_dtype == torch.uint8,
            "vnni_size": 4 if self.input_dtype == torch.uint8 else 2,
            "restrict_keyword": get_restrict_keyword(),
            "is_msvc_compiler": cpp_builder.is_msvc_cl(),
        }

    def get_kernel_declaration(self):
        options = self.get_common_options()
        return KernelTemplate._template_from_string(self.DECLARE_KERNEL).render(options)

    def get_kernel_extra_args_declare(self) -> str:
        return ""

    def get_kernel_extra_args(self) -> str:
        return ""

    def codegen_define(self, kernel: CppTemplateKernel) -> str:
        raise NotImplementedError

    def codegen_call(
        self,
        kernel: CppTemplateKernel,
        A: ir.Buffer,
        B: ir.Buffer,
        C: ir.Buffer,
        accum: bool,
        trans_b: bool = True
    ) -> str:
        """
        Generate the code for calling the templated kernel that computes
        `C += alpha * A @ B` if `accum` is True, or `C = alpha * A @ B` otherwise.
        """
        A_ptr = f"&({kernel.index(A, [0, 0])})"
        # B_ptr = f"&({kernel.index(B, [0, 0])})"
        B_ptr = f"&(W[static_cast<int64_t>(k_start + 2048L*nci)])"
        C_ptr = f"&({kernel.index(C, [0, 0])})"
        M = kernel.size(C, 0)
        N = kernel.size(C, 1)
        K = kernel.size(A, 1)
        lda = kernel.stride(A, 0)
        # ldb = kernel.stride(B, 0)
        # print("B layout: ", B.get_layout())
        ldb = 64
        ldc = kernel.stride(C, 0)
        res = IndentedBuffer()
        res.writeline(f"{self.name}<{value_to_cpp(accum, 'bool')}>(")
        with res.indent():
            extra_args = self.get_kernel_extra_args()
            if extra_args:
                res.writeline(extra_args)
            res.writeline(f"{A_ptr},")
            res.writeline(f"{B_ptr},")
            res.writeline(f"{C_ptr},")
            res.writeline(f"{M},")
            res.writeline(f"{N},")
            res.writeline(f"{K},")
            res.writeline(f"{lda},")
            res.writeline(f"{ldb},")
            if trans_b:
                res.writeline(f"{ldc},")
                res.writeline("true")
            else:
                res.writeline(f"{ldc},")
                res.writeline("false")

        res.writeline(");")
        return res.getvalue()

    def codegen_init(
        self,
        kernel: CppTemplateKernel,
    ) -> str:
        return ""

    def codegen_finalize(
        self,
        kernel: CppTemplateKernel,
    ) -> str:
        return ""

    def get_b_layout(self) -> LayoutType:
        return LayoutType.NORMAL


@dataclasses.dataclass
class CppMicroGemmConfig:
    input_dtype: torch.dtype
    input2_dtype: torch.dtype
    output_dtype: torch.dtype
    compute_dtype: torch.dtype
    vec_isa_cls: Type[VecISA]
    register_blocking: GemmBlocking
    extra_check: Optional[Callable[..., bool]] = None


micro_gemm_configs: Dict[Type[CppMicroGemm], List[CppMicroGemmConfig]] = {}


def register_micro_gemm(*configs):
    def inner(cls):
        assert (
            cls not in micro_gemm_configs
        ), f"Duplicate micro_gemm registration for {cls}"
        assert len(configs) > 0, f"No micro_gemm configs provided for {cls}"
        micro_gemm_configs[cls] = list(configs)
        return cls

    return inner


def generate_gemm_config(
    vec_isa_cls,
    register_blockings,
    input_dtype=torch.float,
    input2_dtype=None,
    output_dtype=None,
    compute_dtype=None,
    extra_check=None,
):
    if output_dtype is None:
        output_dtype = input_dtype
    if compute_dtype is None:
        compute_dtype = output_dtype
    if input2_dtype is None:
        input2_dtype = input_dtype
    return [
        CppMicroGemmConfig(
            input_dtype,
            input2_dtype,
            output_dtype,
            compute_dtype,
            vec_isa_cls,
            GemmBlocking(*blocking),
            extra_check,
        )
        for blocking in register_blockings
    ]


class CppMicroGemmRef(CppMicroGemm):
    """
    A reference implementation of the CppMicroGemm class with naive C++ code.
    It is used for correctness debugging.
    """

    TEMPLATE_ENTRY = r"""
{{declare_kernel}} {
    for (int64_t m = 0; m < M; ++m) {
        for (int64_t n = 0; n < N; ++n) {
            {{compute_t}} result = accum ? C[m * ldc + n] : 0;
            for (int64_t k = 0; k < K; ++k) {
                result += ({{compute_t}})A[m * lda + k] * ({{compute_t}})B[k * ldb + n] * {{alpha}};
            }
            C[m * ldc + n] = result;
        }
    }
}
"""

    def __init__(
        self, name, input_dtype, input2_dtype, output_dtype, compute_dtype, alpha
    ) -> None:
        super().__init__(
            name,
            input_dtype,
            input2_dtype,
            output_dtype,
            compute_dtype,
            GemmBlocking(1, 1, 1),
            alpha,
        )

    def codegen_define(self, kernel: CppTemplateKernel) -> str:
        options = {
            "declare_kernel": self.get_kernel_declaration(),
            **self.get_common_options(),
        }
        return KernelTemplate._template_from_string(self.TEMPLATE_ENTRY).render(options)


@register_micro_gemm(
    *generate_gemm_config(
        VecAVX512,
        [(8, 48, 1), (8, 32, 1), (16, 16, 1)],
        input_dtype=torch.float,
    ),
    *generate_gemm_config(
        VecAVX512,
        [(8, 48, 1), (8, 32, 1), (16, 16, 1)],
        input_dtype=torch.bfloat16,
        output_dtype=torch.float,
    ),
    *generate_gemm_config(
        VecAVX512,
        [(8, 48, 1), (8, 32, 1), (16, 16, 1)],
        input_dtype=torch.half,
        output_dtype=torch.float,
    ),
    *generate_gemm_config(
        VecAVX512,
        [(8, 48, 1), (8, 32, 1), (16, 16, 1)],
        input_dtype=torch.bfloat16,
        input2_dtype=torch.int8,
        output_dtype=torch.float,
        compute_dtype=torch.float,
    ),
    *generate_gemm_config(
        VecAVX2,
        [(4, 24, 1), (4, 16, 1), (8, 8, 1)],
        input_dtype=torch.float,
    ),
    *generate_gemm_config(
        VecAVX2,
        [(4, 24, 1), (4, 16, 1), (8, 8, 1)],
        input_dtype=torch.bfloat16,
        output_dtype=torch.float,
    ),
    *generate_gemm_config(
        VecAVX2,
        [(4, 24, 1), (4, 16, 1), (8, 8, 1)],
        input_dtype=torch.half,
        output_dtype=torch.float,
    ),
    *generate_gemm_config(
        VecAVX2,
        [(4, 24, 1), (4, 16, 1), (8, 8, 1)],
        input_dtype=torch.bfloat16,
        input2_dtype=torch.int8,
        output_dtype=torch.float,
        compute_dtype=torch.float,
    ),
)
class CppMicroGemmFP32Vec(CppMicroGemm):
    """
    This class generates the code for micro gemm using fp32 vec instructions for compute.
    It supports input types of torch.float, torch.bfloat16, and torch.half with fp32 output.
    The output of the microkernel is in FP32, but it would be converted to BF16/FP16 in the template,
    if the desired output is BF16/FP16.
    """

    TEMPLATE_ENTRY = r"""
{{declare_kernel}} {
    {{kernel.assert_function}}(N % {{block_n}} == 0, "N dimension must be multiple of {{block_n}}");
    {{kernel.assert_function}}(K % {{block_k}} == 0, "K dimension must be multiple of {{block_k}}");
    // TODO(jgong5): loop unroll for M and N
    for (int64_t m = 0; m < M; m += {{block_m}}) {
        int64_t block_m = std::min<int64_t>(M - m, {{block_m}});
        for (int64_t n = 0; n < N; n += {{block_n}}) {
            //std::cout << "n: " << n << std::endl;
            if (block_m == {{block_m}}) {
                {{kernel_name}}_kernel<{{block_m}}, {{block_n}}, accum>(
                    A + m * lda,
                    B + (trans_b ? (n * ldb) : n),
                    C + m * ldc + n,
                    K,
                    lda,
                    ldb,
                    ldc,
                    trans_b
                );
            } else {
                switch (block_m) {
{%- for b in range(block_m - 1, 0, -1) %}
                case {{b}}:
                    {{kernel_name}}_kernel<{{b}}, {{block_n}}, accum>(
                        A + m * lda,
                        B + (trans_b ? (n * ldb) : n),
                        C + m * ldc + n,
                        K,
                        lda,
                        ldb,
                        ldc,
                        trans_b
                    );
                    break;
{%- endfor %}
                default:
                    {{kernel.assert_function}}(false, "Unsupported block_m: {{block_m}}");
                }
            }
        }
    }
}
"""

# auto reduce = [&](unsigned int l) {

#     const int depth = at::native::utils::CeilLog2(l);
#     //std::cout << "depth: " << depth << "" << std::endl;
#     for (int d = 0; d < depth; d++) {
#         l = d > 0 ? (l >> 1) : l;
#         //std::cout << "l: " << l << std::endl;
#         for (int i = 0; i < l; i++) {
#             int r = l - 1 - i;
#             if (i < r) {
#                 vmid[i] = vmid[i] + vmid[r];
#             } else if (i == r){
#                 vmid[i - 1] = vmid[i - 1] + vmid[i];
#             } else {
#                 break;
#             }
#         }
#     }
#     auto c = at::vec::vec_reduce_all([](Vectorized& x, Vectorized& y) { return x + y; }, vmid[0]);
#     return c;
# };


            # const int depth = 5;//at::native::utils::CeilLog2(l);
            # //std::cout << "depth: " << depth << "" << std::endl;
            # for (int d = 0; d < depth; d++) {
            #     l = d > 0 ? (l >> 1) : l;
            #     //std::cout << "l: " << l << std::endl;
            #     for (int i = 0; i < l; i++) {
            #         int r = l - 1 - i;
            #         if (i < r) {
            #             vmid[i] = vmid[i] + vmid[r];
            #         } else if (i == r){
            #             vmid[i - 1] = vmid[i - 1] + vmid[i];
            #         } else {
            #             break;
            #         }
            #     }
            # }

#             va[0] = vmid[0] + vmid[1];
#             va[1] = vmid[2] + vmid[3];
#             va[2] = vmid[4] + vmid[5];
#             va[3] = vmid[6] + vmid[7];
#             va[4] = vmid[8] + vmid[9];
#             va[5] = vmid[10] + vmid[11];
#             va[6] = vmid[12] + vmid[13];
#             va[7] = vmid[14] + vmid[15];
#             va[8] = vmid[16] + vmid[17];
#             va[9] = vmid[18] + vmid[19];
#             va[10] = vmid[20] + vmid[21];
#             va[11] = vmid[22] + vmid[23];
#             va[12] = vmid[24] + vmid[25];
#             va[13] = vmid[26] + vmid[27];
#             va[14] = vmid[28] + vmid[29];
#             va[15] = vmid[30] + vmid[31];

#             va[16] = va[0] + va[1];
#             va[17] = va[2] + va[3];
#             va[18] = va[4] + va[5];
#             va[19] = va[6] + va[7];
#             va[20] = va[8] + va[9];
#             va[21] = va[10] + va[11];
#             va[22] = va[12] + va[13];
#             va[23] = va[14] + va[15];

#             va[24] = va[16] + va[17];
#             va[25] = va[18] + va[19];
#             va[26] = va[20] + va[21];
#             va[27] = va[22] + va[23];

#             va[28] = va[24] + va[25];
#             va[29] = va[26] + va[27];
#             va[30] = va[28] + va[29];


# b_in = VectorizedIn2::loadu(B + i * VLEN, elem);
#                 vb[i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 1 * ldb + i * VLEN, elem);
#                 vb[1 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 2 * ldb + i * VLEN, elem);
#                 vb[2 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 3 * ldb + i * VLEN, elem);
#                 vb[3 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 4 * ldb + i * VLEN, elem);
#                 vb[4 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 5 * ldb + i * VLEN, elem);
#                 vb[5 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 6 * ldb + i * VLEN, elem);
#                 vb[6 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 7 * ldb + i * VLEN, elem);
#                 vb[7 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);

#                 b_in = VectorizedIn2::loadu(B + 8 * ldb + i * VLEN, elem);
#                 vb[8 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 9 * ldb + i * VLEN, elem);
#                 vb[9 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 10 * ldb + i * VLEN, elem);
#                 vb[10 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 11 * ldb + i * VLEN, elem);
#                 vb[11 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 12 * ldb + i * VLEN, elem);
#                 vb[12 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 13 * ldb + i * VLEN, elem);
#                 vb[13 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 14 * ldb + i * VLEN, elem);
#                 vb[14 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 15 * ldb + i * VLEN, elem);
#                 vb[15 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);

#                 b_in = VectorizedIn2::loadu(B + 16 * ldb + i * VLEN, elem);
#                 vb[16 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 17 * ldb + i * VLEN, elem);
#                 vb[17 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 18 * ldb + i * VLEN, elem);
#                 vb[18 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 19 * ldb + i * VLEN, elem);
#                 vb[19 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 20 * ldb + i * VLEN, elem);
#                 vb[20 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 21 * ldb + i * VLEN, elem);
#                 vb[21 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 22 * ldb + i * VLEN, elem);
#                 vb[22 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 23 * ldb + i * VLEN, elem);
#                 vb[23 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);

#                 b_in = VectorizedIn2::loadu(B + 24 * ldb + i * VLEN, elem);
#                 vb[24 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 25 * ldb + i * VLEN, elem);
#                 vb[25 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 26 * ldb + i * VLEN, elem);
#                 vb[26 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 27 * ldb + i * VLEN, elem);
#                 vb[27 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 28 * ldb + i * VLEN, elem);
#                 vb[28 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 29 * ldb + i * VLEN, elem);
#                 vb[29 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 30 * ldb + i * VLEN, elem);
#                 vb[30 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);
#                 b_in = VectorizedIn2::loadu(B + 31 * ldb + i * VLEN, elem);
#                 vb[31 * _K + i] = at::vec::convert<{{compute_t}}>(b_in);


    TEMPLATE_KERNEL = r"""

#include <ATen/native/cpu/moments_utils.h>
#include <vector>
template <int64_t BLOCK_M, int64_t BLOCK_N, bool accum>
inline void {{kernel_name}}_kernel(
    const {{input_t}}* {{restrict_keyword}} A,
    const {{input2_t}}* {{restrict_keyword}} B,
    {{output_t}}* {{restrict_keyword}} C,
    int64_t K,
    int64_t lda,
    int64_t ldb,
    int64_t ldc,
    bool trans_b = false
) {
    using Vectorized = at::vec::Vectorized<{{compute_t}}>;
    using VectorizedIn = at::vec::Vectorized<{{input_t}}>;
    constexpr auto VLEN = Vectorized::size();
    if (!trans_b) {
        constexpr auto ROWS = BLOCK_M;
        constexpr auto COLS = BLOCK_N / VLEN;

        Vectorized va;
        at::vec::VectorizedN<{{compute_t}}, COLS> vb;
        at::vec::VectorizedN<{{compute_t}}, ROWS*COLS> vc;

        auto loadc = [&](auto i) {
            if constexpr (accum) {
                constexpr int row = i / COLS;
                constexpr int col = i % COLS;
                vc[i] = Vectorized::loadu(C + row * ldc + col * VLEN);
            } else {
                vc[i] = Vectorized(0.0f);
            }
        };
        c10::ForcedUnroll<ROWS * COLS>{}(loadc);

        auto compute = [&, COLS](auto i, int k) {
            constexpr int row = i / COLS;
            constexpr int col = i % COLS;

            if constexpr (col == 0) {
{%- if alpha != 1 %}
                va = Vectorized(static_cast<{{compute_t}}>(A[row * lda + k]) * {{alpha}});
{%- else %}
                va = Vectorized(static_cast<{{compute_t}}>(A[row * lda + k]));
{%- endif %}
            }

            if constexpr (row == 0) {
{%- if input2_dtype in [torch.bfloat16, torch.float16] %}
                auto b = VectorizedIn::loadu(B + k * ldb + col * VLEN, VLEN);
                vb[col] = at::vec::convert<{{compute_t}}>(b);
{%- elif input2_dtype == torch.int8 %}
                // Convert VLEN int8 elements to int32, and then fp32
                auto b32 = at::vec::convert_to_int32<int8_t>(B + k * ldb + col * VLEN);
                vb[col] = at::vec::convert<float>(b32);
{%- else %}
                vb[col] = Vectorized::loadu(B + k * ldb + col * VLEN);
{%- endif %}
            }

            constexpr int idx = row * COLS + col;
            vc[idx] = at::vec::fmadd(va, vb[col], vc[idx]);
        };

        for (int k = 0; k < K; ++k) {
            c10::ForcedUnroll<ROWS * COLS>{}(compute, k);
        }

        // store to C
        auto storec = [&](auto i) {
            constexpr int row = i / COLS;
            constexpr int col = i % COLS;
            vc[i].store(C + row * ldc + col * VLEN);
        };
        c10::ForcedUnroll<ROWS * COLS>{}(storec);

    } else if (true) {
        // for transpose B case
        using VectorizedIn2 = at::vec::Vectorized<{{input2_t}}>;
        VectorizedIn a_in;
        VectorizedIn b_in;
        auto zero = Vectorized(0.0f);
        int _K = (K + VLEN - 1) / VLEN;
        constexpr int sN = 4;
        constexpr int sM = 4;

        constexpr int bN = (BLOCK_N + sN - 1) / sN;
        constexpr int bM = (BLOCK_M + sM - 1) / sM;
        at::vec::Vectorized<{{compute_t}}> va;
        //at::vec::VectorizedN<{{compute_t}}, sN * _K> vb;
        //std::vector<at::vec::Vectorized<{{compute_t}}>> vb(sN * _K);
        at::vec::Vectorized<{{compute_t}}> vb[sN * _K];
        at::vec::VectorizedN<{{compute_t}}, sN * sM> vmid;
        auto valpha = at::vec::Vectorized<{{compute_t}}>({{alpha}});

        // B inner profuct: B is transposed
        // for B, K dim is contiguous.
        // Note ldb should be ld of N dim for B
        constexpr int ntail = BLOCK_N % sN;
        constexpr int mtail = BLOCK_M % sM;
        constexpr int ktail = 64 % VLEN;

        auto compute_trans = [&](int m, int n, int idk) { // int m, int n, int idk  auto idk, int n, int m
            //constexpr int idk = index % _K;
            //constexpr int m = (index / _K) % bM;
            //constexpr int n = index / _K / bM;
            int e_n = (n == bN - 1 && ntail != 0) ? (BLOCK_N - n * sN) : sN;
            int e_m = (m == bM - 1 && mtail != 0) ? (BLOCK_M - m * sM) : sM;
            //int idk = k * sK + ik;
            int e_k = (idk == _K - 1 && ktail != 0) ? (64 - idk * VLEN) : VLEN;
            if (m == 0) {
                {{kernel.unroll_pragma(4)}}
                for (int i = 0; i < e_n; i++) {
                    b_in = VectorizedIn2::loadu(B + (sN * n + i) * ldb + idk * VLEN, e_k);
                    vb[sN * idk + i] = at::vec::convert<{{compute_t}}>(b_in);
                }
            }
            if (idk == 0) {
                {{kernel.unroll_pragma(4)}}
                for (int s = 0; s < e_m; s++) {
{%- if alpha != 1 %}
                    a_in = VectorizedIn::loadu(A + (sM * m + s) * lda + idk * VLEN, e_k);
                    va = at::vec::convert<{{compute_t}}>(a_in) * valpha;
{%- else %}
                    a_in = VectorizedIn::loadu(A + (sM * m + s) * lda + idk * VLEN, e_k);
                    va = at::vec::convert<{{compute_t}}>(a_in);
{%- endif %}

                    {{kernel.unroll_pragma(4)}}
                    for (int i = 0; i < e_n; i++) {
                        vmid[sN * s + i] = at::vec::fmadd(va, vb[sN * idk + i], zero);
                    }
                }
            } else {
                {{kernel.unroll_pragma(4)}}
                for (int s = 0; s < e_m; s++) {
{%- if alpha != 1 %}
                    a_in = VectorizedIn::loadu(A + (sM * m + s) * lda + idk * VLEN, e_k);
                    va = at::vec::convert<{{compute_t}}>(a_in) * valpha;
{%- else %}
                    a_in = VectorizedIn::loadu(A + (sM * m + s) * lda + idk * VLEN, e_k);
                    va = at::vec::convert<{{compute_t}}>(a_in);
{%- endif %}
                    {{kernel.unroll_pragma(4)}}
                    for (int i = 0; i < e_n; i++) {
                        vmid[sN * s + i] = at::vec::fmadd(va, vb[sN * idk + i], vmid[sN * s + i]);
                    }
                }
            }

            // store to C
            if (idk == _K - 1) {
                {{kernel.unroll_pragma(4)}}
                for (int s = 0; s < e_m; s++) {
                    {{kernel.unroll_pragma(4)}}
                    for (int i = 0; i < e_n; i++) {
                        auto v = at::vec::vec_reduce_all([](Vectorized& x, Vectorized& y) { return x + y; }, vmid[sN * s + i]);
                        if constexpr (accum) {
                            auto c = *(C + (sM * m + s) * ldc + sN * n + i);
                            *(C + (sM * m + s) * ldc + sN * n + i) = c + v;
                        } else {
                            *(C + (sM * m + s) * ldc + sN * n + i) = v;
                        }
                    }
                }
            }
        };

        for (int n = 0; n < bN; ++n) {
            for (int m = 0; m < bM; ++m) {
                //for (int k = 0; k < bK; ++k) {
                //    c10::ForcedUnroll<sK>{}(compute_trans, m, n, k);
                //}

                {{kernel.unroll_pragma(4)}}
                for (int k = 0; k < _K; ++k) {
                    compute_trans(m, n, k);
                }
            }
        }
        //c10::ForcedUnroll<bN * bM * _K>{}(compute_trans);

    } else if (false) { // transpose + gemm
        constexpr auto ROWS = BLOCK_M;
        constexpr auto COLS = BLOCK_N / VLEN;
        int _K = K / VLEN;
        Vectorized va;
        at::vec::VectorizedN<{{compute_t}}, VLEN> vb;
        at::vec::VectorizedN<{{compute_t}}, ROWS*COLS> vc;

        auto loadc = [&](auto i) {
            if constexpr (accum) {
                constexpr int row = i / COLS;
                constexpr int col = i % COLS;
                vc[i] = Vectorized::loadu(C + row * ldc + col * VLEN);
            } else {
                vc[i] = Vectorized(0.0f);
            }
        };
        c10::ForcedUnroll<ROWS * COLS>{}(loadc);

        auto compute = [&, COLS](auto i, int k) {
            constexpr int row = i % ROWS;
            constexpr int col = i / ROWS;
            constexpr int e_col = col * VLEN;
            int idk = k * VLEN;

            if constexpr (row == 0) {
                auto b = VectorizedIn::loadu(B + e_col * ldb + idk, VLEN);
                vb[0] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 1) * ldb + idk, VLEN);
                vb[1] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 2) * ldb + idk, VLEN);
                vb[2] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 3) * ldb + idk, VLEN);
                vb[3] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 4) * ldb + idk, VLEN);
                vb[4] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 5) * ldb + idk, VLEN);
                vb[5] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 6) * ldb + idk, VLEN);
                vb[6] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 7) * ldb + idk, VLEN);
                vb[7] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 8) * ldb + idk, VLEN);
                vb[8] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 9) * ldb + idk, VLEN);
                vb[9] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 10) * ldb + idk, VLEN);
                vb[10] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 11) * ldb + idk, VLEN);
                vb[11] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 12) * ldb + idk, VLEN);
                vb[12] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 13) * ldb + idk, VLEN);
                vb[13] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 14) * ldb + idk, VLEN);
                vb[14] = at::vec::convert<{{compute_t}}>(b);
                b = VectorizedIn::loadu(B + (e_col + 15) * ldb + idk, VLEN);
                vb[15] = at::vec::convert<{{compute_t}}>(b);
                at::vec::VectorizedN<{{compute_t}}, VLEN> vb_trans;
                vb_trans[0] = _mm512_unpacklo_ps(vb[0], vb[1]);
                vb_trans[1] = _mm512_unpackhi_ps(vb[0], vb[1]);
                vb_trans[2] = _mm512_unpacklo_ps(vb[2], vb[3]);
                vb_trans[3] = _mm512_unpackhi_ps(vb[2], vb[3]);
                vb_trans[4] = _mm512_unpacklo_ps(vb[4], vb[5]);
                vb_trans[5] = _mm512_unpackhi_ps(vb[4], vb[5]);
                vb_trans[6] = _mm512_unpacklo_ps(vb[6], vb[7]);
                vb_trans[7] = _mm512_unpackhi_ps(vb[6], vb[7]);
                vb_trans[8] = _mm512_unpacklo_ps(vb[8], vb[9]);
                vb_trans[9] = _mm512_unpackhi_ps(vb[8], vb[9]);
                vb_trans[10] = _mm512_unpacklo_ps(vb[10], vb[11]);
                vb_trans[11] = _mm512_unpackhi_ps(vb[10], vb[11]);
                vb_trans[12] = _mm512_unpacklo_ps(vb[12], vb[13]);
                vb_trans[13] = _mm512_unpackhi_ps(vb[12], vb[13]);
                vb_trans[14] = _mm512_unpacklo_ps(vb[14], vb[15]);
                vb_trans[15] = _mm512_unpackhi_ps(vb[14], vb[15]);
                vb[0] = _mm512_castpd_ps(
                    _mm512_unpacklo_pd(_mm512_castps_pd(vb_trans[0]), _mm512_castps_pd(vb_trans[2])));
                vb[1] = _mm512_castpd_ps(
                    _mm512_unpackhi_pd(_mm512_castps_pd(vb_trans[0]), _mm512_castps_pd(vb_trans[2])));
                vb[2] = _mm512_castpd_ps(
                    _mm512_unpacklo_pd(_mm512_castps_pd(vb_trans[1]), _mm512_castps_pd(vb_trans[3])));
                vb[3] = _mm512_castpd_ps(
                    _mm512_unpackhi_pd(_mm512_castps_pd(vb_trans[1]), _mm512_castps_pd(vb_trans[3])));
                vb[4] = _mm512_castpd_ps(
                    _mm512_unpacklo_pd(_mm512_castps_pd(vb_trans[4]), _mm512_castps_pd(vb_trans[6])));
                vb[5] = _mm512_castpd_ps(
                    _mm512_unpackhi_pd(_mm512_castps_pd(vb_trans[4]), _mm512_castps_pd(vb_trans[6])));
                vb[6] = _mm512_castpd_ps(
                    _mm512_unpacklo_pd(_mm512_castps_pd(vb_trans[5]), _mm512_castps_pd(vb_trans[7])));
                vb[7] = _mm512_castpd_ps(
                    _mm512_unpackhi_pd(_mm512_castps_pd(vb_trans[5]), _mm512_castps_pd(vb_trans[7])));
                vb[8] = _mm512_castpd_ps(
                    _mm512_unpacklo_pd(_mm512_castps_pd(vb_trans[8]), _mm512_castps_pd(vb_trans[10])));
                vb[9] = _mm512_castpd_ps(
                    _mm512_unpackhi_pd(_mm512_castps_pd(vb_trans[8]), _mm512_castps_pd(vb_trans[10])));
                vb[10] = _mm512_castpd_ps(
                    _mm512_unpacklo_pd(_mm512_castps_pd(vb_trans[9]), _mm512_castps_pd(vb_trans[11])));
                vb[11] = _mm512_castpd_ps(
                    _mm512_unpackhi_pd(_mm512_castps_pd(vb_trans[9]), _mm512_castps_pd(vb_trans[11])));
                vb[12] = _mm512_castpd_ps(
                    _mm512_unpacklo_pd(_mm512_castps_pd(vb_trans[12]), _mm512_castps_pd(vb_trans[14])));
                vb[13] = _mm512_castpd_ps(
                    _mm512_unpackhi_pd(_mm512_castps_pd(vb_trans[12]), _mm512_castps_pd(vb_trans[14])));
                vb[14] = _mm512_castpd_ps(
                    _mm512_unpacklo_pd(_mm512_castps_pd(vb_trans[13]), _mm512_castps_pd(vb_trans[15])));
                vb[15] = _mm512_castpd_ps(
                    _mm512_unpackhi_pd(_mm512_castps_pd(vb_trans[13]), _mm512_castps_pd(vb_trans[15])));

                vb_trans[0] = _mm512_shuffle_f32x4(vb[0], vb[4], 0x88);
                vb_trans[1] = _mm512_shuffle_f32x4(vb[1], vb[5], 0x88);
                vb_trans[2] = _mm512_shuffle_f32x4(vb[2], vb[6], 0x88);
                vb_trans[3] = _mm512_shuffle_f32x4(vb[3], vb[7], 0x88);
                vb_trans[4] = _mm512_shuffle_f32x4(vb[0], vb[4], 0xdd);
                vb_trans[5] = _mm512_shuffle_f32x4(vb[1], vb[5], 0xdd);
                vb_trans[6] = _mm512_shuffle_f32x4(vb[2], vb[6], 0xdd);
                vb_trans[7] = _mm512_shuffle_f32x4(vb[3], vb[7], 0xdd);
                vb_trans[8] = _mm512_shuffle_f32x4(vb[8], vb[12], 0x88);
                vb_trans[9] = _mm512_shuffle_f32x4(vb[9], vb[13], 0x88);
                vb_trans[10] = _mm512_shuffle_f32x4(vb[10], vb[14], 0x88);
                vb_trans[11] = _mm512_shuffle_f32x4(vb[11], vb[15], 0x88);
                vb_trans[12] = _mm512_shuffle_f32x4(vb[8], vb[12], 0xdd);
                vb_trans[13] = _mm512_shuffle_f32x4(vb[9], vb[13], 0xdd);
                vb_trans[14] = _mm512_shuffle_f32x4(vb[10], vb[14], 0xdd);
                vb_trans[15] = _mm512_shuffle_f32x4(vb[11], vb[15], 0xdd);

                vb[0] = _mm512_shuffle_f32x4(vb_trans[0], vb_trans[8], 0x88);
                vb[1] = _mm512_shuffle_f32x4(vb_trans[1], vb_trans[9], 0x88);
                vb[2] = _mm512_shuffle_f32x4(vb_trans[2], vb_trans[10], 0x88);
                vb[3] = _mm512_shuffle_f32x4(vb_trans[3], vb_trans[11], 0x88);
                vb[4] = _mm512_shuffle_f32x4(vb_trans[4], vb_trans[12], 0x88);
                vb[5] = _mm512_shuffle_f32x4(vb_trans[5], vb_trans[13], 0x88);
                vb[6] = _mm512_shuffle_f32x4(vb_trans[6], vb_trans[14], 0x88);
                vb[7] = _mm512_shuffle_f32x4(vb_trans[7], vb_trans[15], 0x88);
                vb[8] = _mm512_shuffle_f32x4(vb_trans[0], vb_trans[8], 0xdd);
                vb[9] = _mm512_shuffle_f32x4(vb_trans[1], vb_trans[9], 0xdd);
                vb[10] = _mm512_shuffle_f32x4(vb_trans[2], vb_trans[10], 0xdd);
                vb[11] = _mm512_shuffle_f32x4(vb_trans[3], vb_trans[11], 0xdd);
                vb[12] = _mm512_shuffle_f32x4(vb_trans[4], vb_trans[12], 0xdd);
                vb[13] = _mm512_shuffle_f32x4(vb_trans[5], vb_trans[13], 0xdd);
                vb[14] = _mm512_shuffle_f32x4(vb_trans[6], vb_trans[14], 0xdd);
                vb[15] = _mm512_shuffle_f32x4(vb_trans[7], vb_trans[15], 0xdd);
            }

            constexpr int idx = row * COLS + col;

            #pragma unroll
            for (int i = 0; i < 16; i++) {
{%- if alpha != 1 %}
                    va = Vectorized(static_cast<{{compute_t}}>(A[row * lda + idk + i]) * {{alpha}});
{%- else %}
                    va = Vectorized(static_cast<{{compute_t}}>(A[row * lda + idk + i]));
{%- endif %}
                vc[idx] = at::vec::fmadd(va, vb[i], vc[idx]);
            }

        };

        for (int k = 0; k < _K; ++k) {
            c10::ForcedUnroll<ROWS * COLS>{}(compute, k);
        }

        // store to C
        auto storec = [&](auto i) {
            constexpr int row = i / COLS;
            constexpr int col = i % COLS;
            vc[i].store(C + row * ldc + col * VLEN);
        };
        c10::ForcedUnroll<ROWS * COLS>{}(storec);

    }
}
"""

    def codegen_define(self, kernel: CppTemplateKernel) -> str:
        options = {
            "declare_kernel": self.get_kernel_declaration(),
            "kernel": kernel,
            "block_m": self.register_blocking.block_m,
            "block_n": self.register_blocking.block_n,
            "block_k": self.register_blocking.block_k,
            "restrict_keyword": get_restrict_keyword(),
            **self.get_common_options(),
        }
        result = KernelTemplate._template_from_string(self.TEMPLATE_KERNEL).render(
            options
        )
        result += KernelTemplate._template_from_string(self.TEMPLATE_ENTRY).render(
            options
        )
        return result


# extra check for CppMicroGemmAMX
def check_amx_extra(config, m, n, k, alpha, num_threads):
    return False
    vnni_size = 4 if config.input_dtype == torch.uint8 else 2
    return k % vnni_size == 0 and alpha == 1


@register_micro_gemm(
    *generate_gemm_config(
        VecAMX,
        [(32, 32, 32), (48, 16, 32), (16, 48, 32)],
        input_dtype=torch.bfloat16,
        input2_dtype=torch.int8,
        output_dtype=torch.float,
        compute_dtype=torch.float,
        extra_check=check_amx_extra,
    ),
    *generate_gemm_config(
        VecAMX,
        [(32, 32, 32), (48, 16, 32), (16, 48, 32)],
        input_dtype=torch.bfloat16,
        output_dtype=torch.float,
        extra_check=check_amx_extra,
    ),
    *generate_gemm_config(
        VecAMX,
        [(32, 32, 64), (48, 16, 64)],
        input_dtype=torch.uint8,
        input2_dtype=torch.int8,
        output_dtype=torch.int32,
        compute_dtype=torch.int32,
        extra_check=check_amx_extra,
    ),
)
class CppMicroGemmAMX(CppMicroGemm):
    """
    This class generates the code for micro gemm using Advanced Matrix eXtention (AMX)
    instructions available in 4th generation Intel Xeon for compute.
    It supports input types of torch.bfloat16 with fp32 output.
    """

    TEMPLATE_ENTRY = r"""
#include <iostream>
{{declare_kernel}} {
    {{kernel.assert_function}}(N % {{block_n}} == 0, "N dimension must be multiple of {{block_n}}");
    {{kernel.assert_function}}(K % 2 == 0, "K dimension must be multiple of 2");
std::cout << "M: " << M << " N: " << N << " K: " << K << std::endl;
std::cout << "lda: " << lda << " ldb: " << ldb << " ldc: " << ldc << std::endl;
{%- if use_cached_dequantized_B %}
    // Create a stack-allocated buffer for tiles of B.
    // Except maybe for the tail-case, an AMX tile of B has 16x32 BF16 elements.
    const auto num_elements_per_b_tile = 512;
    const auto last_k_offset = K / {{block_k}} * {{block_k}};
    const auto tail_k_size = K - last_k_offset;
    // we cache K * {{block_n}} elements of dequantized B
    const auto buf_size = K * {{block_n}} * sizeof({{input_t}});
    {%- if is_msvc_compiler %}
    // MSVC doesn't support stack-allocated dynamic-sized arrays, so using heap memory here.
    std::unique_ptr<{{input_t}}[]> heap_deq_b_buf_ptr(new {{input_t}}[buf_size]);
    {{input_t}}* dequantized_B_buf = heap_deq_b_buf_ptr.get();
    {%- else %}
    // It's safe to use a stack-allocated array since the blocking strategy would
    // require us to allocate an array that's smaller than the size of L1D cache,
    // and the default per thread max stack size on Linux is quite higher,
    // so we need not worry about stack overflow.
    alignas(4096) {{input_t}} dequantized_B_buf[buf_size];
    {%- endif %}

    const auto b_tile_ptr_stride = ldb * {{vnni_size}};

    auto load_B_row = [&]({{input2_t}}* {{restrict_keyword}} src, {{input_t}}* {{restrict_keyword}} dst) {
        auto b_int8 = at::vec::Vectorized<int8_t>::loadu(src, static_cast<int64_t>(32));
        auto b_bf16 = at::vec::convert<{{input_t}}>(b_int8);
        b_bf16.store(dst);
    };

    auto load_B_tile = [&]({{input2_t}}* B_ptr, int idx, int num_b_rows) {
        {{input_t}}* base_addr = dequantized_B_buf + idx;
        {{kernel.unroll_pragma(8)}}
        for (int i = 0; i < num_b_rows; i++) {
            load_B_row(
                B_ptr + i * b_tile_ptr_stride,
                base_addr + i * 32
            );
        }
    };
    auto load_dequantized_B = [&](int n) {
        // Load a tile of B & cache it in L1D.
        {{kernel.unroll_pragma(4)}}
        for (int k = 0; k < K; k += {{block_k}}) {
            int num_b_rows = (k < last_k_offset) ? 16 : tail_k_size;
            {{kernel.unroll_pragma(2)}}
            for (int tile_col = 0; tile_col <= 1; tile_col++) {
                load_B_tile(
                    const_cast<{{input2_t}}*>(B) + n + k * ldb + tile_col * {{16 * vnni_size}},
                    (k / {{block_k // 2}} + tile_col) * num_elements_per_b_tile,
                    num_b_rows
                );
            }
        }
    };
{%- endif %}
    // TODO(jgong5): loop unroll for M and N
    for (int64_t n = 0; n < N; n += {{block_n}}) {
{%- if use_cached_dequantized_B %}
        // Dequantize K * 32 int8 B elements into BF16
        load_dequantized_B(n);
{%- endif %}
        for (int64_t m = 0; m < M; m += {{block_m}}) {
            int64_t block_m = std::min<int64_t>(M - m, {{block_m}});
            int64_t m_tail = m;
{%- for num_rows in range(block_m, 0, -16) %}
    {%- if num_rows != block_m %}
            else
    {%- endif %}
            if (block_m >= {{num_rows}}) {
                {{kernel_name}}_amx_kernel_{{num_rows}}_{{num_columns}}<accum>(
                    amx_state,
                    A + m * lda,
{%- if use_cached_dequantized_B %}
                    dequantized_B_buf,
{%- else %}
                    B + n,
{%- endif %}
                    C + m * ldc + n,
                    K,
                    lda,
                    ldb,
                    ldc,
                    16
                );
                block_m -= {{num_rows}};
                m_tail += {{num_rows}};
            }
{%- endfor %}
            if (block_m > 0) {
                {{kernel_name}}_amx_kernel_16_{{num_columns}}<accum>(
                    amx_state,
                    A + m_tail * lda,
{%- if use_cached_dequantized_B %}
                    dequantized_B_buf,
{%- else %}
                    B + n,
{%- endif %}
                    C + m_tail * ldc + n,
                    K,
                    lda,
                    ldb,
                    ldc,
                    block_m
                );
            }
        }
    }
}
"""

    TEMPLATE_KERNEL = r"""

template <bool accum>
inline void {{kernel_name}}_amx_kernel_{{num_rows}}_{{num_columns}}(
    AMXState& amx_state,
    const {{input_t}}* {{restrict_keyword}} A,
{%- if use_cached_dequantized_B %}
    const {{input_t}}* {{restrict_keyword}} B,
{%- else %}
    const {{input2_t}}* {{restrict_keyword}} B,
{%- endif %}
    {{output_t}}* {{restrict_keyword}} C,
    int64_t K,
    int64_t lda,
    int64_t ldb,
    int64_t ldc,
    uint8_t tilecfg_rows
) {
    // TODO(jgong5): add prefetch hint for A, B, C
    auto loadconfig = [](const amx_tilecfg& cfg) {
        _tile_loadconfig(&cfg);
    };
    const auto last_k_offset = K / {{block_k}} * {{block_k}};
    const auto tail_k_size = K - last_k_offset;
    if C10_LIKELY (last_k_offset > 0) {
        amx_state.configure(tilecfg_rows, 64, {{num_rows}} / 16, {{num_columns}}, loadconfig);
    } else {
        amx_state.configure(tilecfg_rows, tail_k_size * sizeof({{input_t}}), {{num_rows}} / 16, {{num_columns}}, loadconfig);
    }
    auto load_c = [&]() {
{%- for tile_row in range(num_rows // 16) %}
    {%- for tile_col in range(num_columns) %}
        {%- set tile_idx = tile_row * num_columns + tile_col %}
        _tile_loadd({{tile_idx}}, C + {{tile_row * 16}} * ldc + {{tile_col * 16}}, ldc * sizeof({{output_t}}));
    {%- endfor %}
{%- endfor %}
    };
    auto zero_c = [&]() {
{%- for tile_row in range(num_rows // 16) %}
    {%- for tile_col in range(num_columns) %}
        {%- set tile_idx = tile_row * num_columns + tile_col %}
        _tile_zero({{tile_idx}});
    {%- endfor %}
{%- endfor %}
    };

    if constexpr (accum) {
        load_c();
    } else {
        zero_c();
    }

    auto compute = [&](int k) {
{%- if use_cached_dequantized_B %}
    // base index for dequantized B
    const auto num_elements_per_b_tile = 512;
    const auto base_idx_of_deq_B = (k / {{block_k // 2}}) * num_elements_per_b_tile;
{%- endif %}
{%- set tile_offset_a = num_rows // 16 * num_columns %}
{%- set tile_offset_b = tile_offset_a + num_rows // 16 %}
{%- for tile_row in range(num_rows // 16) %}
    {%- for tile_col in range(num_columns) %}
        {%- set tile_idx_a = tile_offset_a + tile_row %}
        {%- set tile_idx_b = tile_offset_b + tile_col %}
        {%- set tile_idx_c = tile_row * num_columns + tile_col %}
        {%- if tile_col == 0 %}
        _tile_stream_loadd({{tile_idx_a}}, A + {{tile_row * 16}} * lda + k, lda * sizeof({{input_t}}));
        {%- endif %}
        {%- if tile_row == 0 %}
            {%- if use_cached_dequantized_B %}
        _tile_loadd({{tile_idx_b}}, B + base_idx_of_deq_B + {{tile_col}} * num_elements_per_b_tile, 64);
            {%- else %}
        _tile_loadd({{tile_idx_b}}, B + k * ldb + {{tile_col * 16 * vnni_size}}, ldb * {{vnni_size}} * sizeof({{input_t}}));
            {%- endif %}
        {%- endif %}
        {%- if int8_gemm %}
        _tile_dpbusd({{tile_idx_c}}, {{tile_idx_a}}, {{tile_idx_b}});
        {%- else %}
        _tile_dpbf16ps({{tile_idx_c}}, {{tile_idx_a}}, {{tile_idx_b}});
        {%- endif %}
    {%- endfor %}
{%- endfor %}
    };

    {{kernel.unroll_pragma(4)}}
    for (int k = 0; k < last_k_offset; k += {{block_k}}) {
        compute(k);
    }

    auto store_c = [&]() {
    // store to C
{%- for tile_row in range(num_rows // 16) %}
    {%- for tile_col in range(num_columns) %}
        {%- set tile_idx = tile_row * num_columns + tile_col %}
        _tile_stored({{tile_idx}}, C + {{tile_row * 16}} * ldc + {{tile_col * 16}}, ldc * sizeof({{output_t}}));
    {%- endfor %}
{%- endfor %}
    };

    // TODO(jgong5): move tail k computation to separate loopnest to save tile configuration overhead
    if C10_UNLIKELY (tail_k_size > 0) {
        if C10_LIKELY (last_k_offset > 0) {
            store_c();
            amx_state.configure(tilecfg_rows, tail_k_size * sizeof({{input_t}}), {{num_rows}} / 16, {{num_columns}}, loadconfig);
            load_c();
        }
        compute(last_k_offset);
    }

    store_c();
}
"""

    def codegen_define(self, kernel: CppTemplateKernel) -> str:
        block_m, block_n, block_k = self.register_blocking
        assert block_m % 16 == 0, "Only support block_m % 16 == 0 for AMX"
        assert block_n % 16 == 0, "Only support block_n % 16 == 0 for AMX"
        if self.input_dtype == torch.uint8:
            assert block_k == 64, "Only support block_k = 64 for AMX INT8"
        else:
            assert block_k == 32, "Only support block_k = 32 for AMX Bfloat16/Float16"
        num_columns = block_n // 16
        options = {
            "declare_kernel": self.get_kernel_declaration(),
            "use_cached_dequantized_B": self.input_dtype == torch.bfloat16
            and self.input2_dtype == torch.int8,
            "kernel": kernel,
            "block_m": block_m,
            "block_n": block_n,
            "block_k": block_k,
            "num_columns": num_columns,
            "restrict_keyword": get_restrict_keyword(),
            **self.get_common_options(),
        }
        result = ""
        for num_rows in range(block_m, 0, -16):
            amx_kernel_options = {**options, "num_rows": num_rows}
            result += KernelTemplate._template_from_string(self.TEMPLATE_KERNEL).render(
                amx_kernel_options
            )
        result += KernelTemplate._template_from_string(self.TEMPLATE_ENTRY).render(
            options
        )
        return result

    def codegen_init(
        self,
        kernel: CppTemplateKernel,
    ) -> str:
        return "AMXState amx_state;"

    def codegen_finalize(
        self,
        kernel: CppTemplateKernel,
    ) -> str:
        return "amx_state.release([]() { _tile_release(); });"

    def get_kernel_extra_args_declare(self) -> str:
        return "AMXState& amx_state,"

    def get_kernel_extra_args(self) -> str:
        return "amx_state,"

    def get_b_layout(self):
        if self.input_dtype == torch.uint8:
            return LayoutType.VNNI4
        else:
            return LayoutType.VNNI2


# extra check for CppMicroBrgemm
def check_brgemm_extra(config, m, n, k, alpha, num_threads):
    assert config.input_dtype == torch.half and config.output_dtype == torch.float
    vnni_size = 2
    # use brgemm for Half when amx_fp16 is supported
    return torch.cpu._is_amx_fp16_supported() and k % vnni_size == 0 and alpha == 1


@register_micro_gemm(
    *generate_gemm_config(
        VecAMX,
        [(32, 32, 32), (48, 16, 32), (16, 48, 32)],
        input_dtype=torch.half,
        output_dtype=torch.float,
        extra_check=check_brgemm_extra,
    ),
)
class CppMicroBrgemm(CppMicroGemm):
    """
    This class generates the code for micro gemm using oneDNN brgemm.
    It supports input types of torch.half.
    """
#     DECLARE_KERNEL = r"""
# template <bool accum>
# inline void {{kernel_name}}(
# {%- if kernel_extra_args_declare %}
#     {{kernel_extra_args_declare}}
# {%- endif %}
#     at::native::cpublas::GemmHelper * brgemm,
#     const {{input_t}}* {{restrict_keyword}} A,
#     const {{input2_t}}* {{restrict_keyword}} B,
#     {{output_t}}* {{restrict_keyword}} C
# )
# """

    TEMPLATE_ENTRY = r"""
#include <ATen/native/CPUBlas.h>
//#include <iostream>
{{declare_kernel}} {
    //std::cout << "M: " << M << " N: " << N << " K: " << K << std::endl;
    //std::cout << "lda: " << lda << " ldb: " << ldb << " ldc: " << ldc << std::endl;
    at::native::cpublas::brgemm(
      M, N, K,
      lda, ldb, ldc,
      accum,
      A,
      B,
      C);
    //at::native::cpublas::brgemm_execute(
    //  brgemm,
    //  A,
    //  B,
    //  C);
}
"""

#     def codegen_init(
#         self,
#         kernel: CppTemplateKernel,
#     ) -> str:
#         return r"""
#         auto brgemm1 = at::native::cpublas::brgemm_create(
#                  64,
#                  32,
#                  64,
#                  64,
#                  32,
#                  32,
#                  false,
#                  at::ScalarType::Half,
#                  at::ScalarType::Half,
#                  at::ScalarType::Float);
#         auto brgemm2 = at::native::cpublas::brgemm_create(
#                  64,
#                  32,
#                  64,
#                  64,
#                  32,
#                  32,
#                  true,
#                  at::ScalarType::Half,
#                  at::ScalarType::Half,
#                  at::ScalarType::Float);        
# """

#     def codegen_call(
#         self,
#         kernel: CppTemplateKernel,
#         A: ir.Buffer,
#         B: ir.Buffer,
#         C: ir.Buffer,
#         accum: bool,
#     ) -> str:
#         """
#         Generate the code for calling the templated kernel that computes
#         `C += alpha * A @ B` if `accum` is True, or `C = alpha * A @ B` otherwise.
#         """
#         A_ptr = f"&({kernel.index(A, [0, 0])})"
#         B_ptr = f"&({kernel.index(B, [0, 0])})"
#         C_ptr = f"&({kernel.index(C, [0, 0])})"
#         M = kernel.size(C, 0)
#         N = kernel.size(C, 1)
#         K = kernel.size(A, 1)
#         lda = kernel.stride(A, 0)
#         ldb = kernel.stride(B, 0)
#         ldc = kernel.stride(C, 0)
#         res = IndentedBuffer()
#         res.writeline(f"{self.name}<{value_to_cpp(accum, 'bool')}>(")
#         with res.indent():
#             extra_args = self.get_kernel_extra_args()
#             if extra_args:
#                 res.writeline(extra_args)
#             if accum:
#                 res.writeline(f"brgemm2,")
#             else:
#                 res.writeline(f"brgemm1,")
#             res.writeline(f"{A_ptr},")
#             res.writeline(f"{B_ptr},")
#             res.writeline(f"{C_ptr}")
#         res.writeline(");")
#         return res.getvalue()

    def codegen_define(self, kernel: CppTemplateKernel) -> str:
        options = {
            "declare_kernel": self.get_kernel_declaration(),
            "kernel": kernel,
            "block_m": self.register_blocking.block_m,
            "block_n": self.register_blocking.block_n,
            "block_k": self.register_blocking.block_k,
            "restrict_keyword": get_restrict_keyword(),
            **self.get_common_options(),
        }
        result = ""
        result += KernelTemplate._template_from_string(self.TEMPLATE_ENTRY).render(
            options
        )
        return result

    def codegen_finalize(
        self,
        kernel: CppTemplateKernel,
    ) -> str:
        return "at::native::cpublas::brgemm_release();"

    def get_b_layout(self):
        assert self.input_dtype == torch.half and torch.cpu._is_amx_fp16_supported()
        return LayoutType.VNNI2


def create_micro_gemm(
    name,
    m,
    n,
    k,
    input_dtype,
    input2_dtype,
    output_dtype=None,
    compute_dtype=None,
    alpha=1,
    num_threads=-1,
    use_ref=True,
) -> Optional[CppMicroGemm]:
    def create_from_config(cls, config: CppMicroGemmConfig):
        return cls(
            name,
            config.input_dtype,
            config.input2_dtype,
            config.output_dtype,
            config.compute_dtype,
            config.register_blocking,
            alpha,
        )

    assert isinstance(n, int) or n.is_number, n
    assert isinstance(k, int) or k.is_number, k
    m = V.graph.sizevars.size_hint(m, fallback=1) if isinstance(m, sympy.Expr) else m
    assert isinstance(m, int), m
    if output_dtype is None:
        output_dtype = input_dtype
    if compute_dtype is None:
        compute_dtype = output_dtype
    if num_threads < 0:
        num_threads = parallel_num_threads()
    vec_isa = pick_vec_isa()
    matched_configs = []
    for cls, configs in micro_gemm_configs.items():
        for config in configs:
            if not issubclass(vec_isa.__class__, config.vec_isa_cls):
                continue
            if (
                config.input_dtype == input_dtype
                and config.compute_dtype == compute_dtype
                and config.input2_dtype == input2_dtype
                and config.output_dtype == output_dtype
                # The output_dtype here is the output dtype of the micro-kernel.
                # In some cases, the actual output dtype of the op for which the micro-kernel
                # is being created would be same as that of the activation, but the micro-kernels
                # compute output in Float/int32, which is converted in the GEMM template. This is
                # subject to change in the future.
            ):
                if config.extra_check is not None and not config.extra_check(
                    config, m, n, k, alpha, num_threads
                ):
                    continue
                block_m, block_n, block_k = config.register_blocking
                if (
                    config.vec_isa_cls == VecAMX
                    and m < block_m
                    and input_dtype == torch.bfloat16
                    and input2_dtype == torch.int8
                ):
                    # For int8 WoQ GEMM, AMX micro-kernel may not perform well if m < block_m
                    continue
                # Criteria on the ranking of configurations
                # 1. ISA: AMX > VEC
                # 2. Dividable by block sizes (block_m, block_n, block_k)
                # 3. Number of mxn blocks is large enough to occupy all the threads
                # 4. Register blocks are larger
                isa_score = 0
                if config.vec_isa_cls == VecAMX:
                    isa_score += 1
                dividable_score = 0
                if m % block_m == 0:
                    dividable_score += 1
                if n % block_n == 0:
                    dividable_score += 1
                if k % block_k == 0:
                    dividable_score += 1
                occupancy_score = 0
                n_blocks = (n + block_n - 1) // block_n
                total_mxn_blocks = n_blocks * ((m + block_m - 1) // block_m)
                if n_blocks >= num_threads:
                    occupancy_score += 1
                if total_mxn_blocks >= num_threads:
                    occupancy_score += 1
                register_bytes = (
                    block_m * block_n * config.compute_dtype.itemsize
                    + (block_m * block_k + block_k * block_n)
                    * config.input_dtype.itemsize
                )
                matched_configs.append(
                    (
                        (isa_score, dividable_score, occupancy_score, register_bytes),
                        cls,
                        config,
                    )
                )
    if len(matched_configs) == 0:
        if use_ref:
            return CppMicroGemmRef(
                name, input_dtype, input2_dtype, output_dtype, compute_dtype, alpha
            )
        else:
            return None
    # TODO(jgong5): allow autotuning on choices of configs
    return create_from_config(*max(matched_configs, key=lambda x: x[0])[1:])
